#!/usr/bin/env python3
"""One-off: backfill ``metadata.daily_stars`` and ``stars_baseline_date``.

Walks ``knowledge/articles/<date>/`` and adds star-delta fields by looking
back up to ``DEFAULT_LOOKBACK_DAYS`` days for a baseline. Existing per-day
files are rewritten in-place; ``index.json`` is then regenerated by deduping
on ``source_url`` and keeping the entry with the latest ``collected_at``.

Idempotent: re-running on already-enriched files yields the same result.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from workflows.star_history import (  # noqa: E402  (import after sys.path tweak)
    DEFAULT_LOOKBACK_DAYS,
    find_baseline_stars,
)


LOGGER = logging.getLogger(__name__)
ARTICLES_DIR = PROJECT_ROOT / "knowledge" / "articles"
DATE_DIR_PATTERN = "????-??-??"


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description="Backfill daily_stars fields.")
    parser.add_argument(
        "--articles-dir",
        type=Path,
        default=ARTICLES_DIR,
        help="Articles directory (default: knowledge/articles).",
    )
    parser.add_argument(
        "--max-lookback-days",
        type=int,
        default=DEFAULT_LOOKBACK_DAYS,
        help="Maximum days to look back for a baseline (default: 3).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print intended changes without writing files.",
    )
    return parser.parse_args()


def backfill_directory(
    articles_dir: Path,
    *,
    max_lookback_days: int,
    dry_run: bool,
) -> tuple[int, int]:
    """Backfill all per-day article files under ``articles_dir``.

    Returns:
        ``(scanned, updated)`` counts.
    """
    scanned = 0
    updated = 0
    for date_dir in sorted(articles_dir.glob(DATE_DIR_PATTERN)):
        if not date_dir.is_dir():
            continue
        date = date_dir.name
        for file_path in sorted(date_dir.glob("*.json")):
            scanned += 1
            try:
                data = json.loads(file_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                LOGGER.warning("[Backfill] failed to read %s", file_path)
                continue
            if not isinstance(data, dict):
                continue
            metadata = data.get("metadata")
            if not isinstance(metadata, dict):
                metadata = {}
            new_metadata = _enrich_metadata(
                metadata,
                source_url=str(data.get("source_url") or ""),
                today_date=date,
                articles_dir=articles_dir,
                max_lookback_days=max_lookback_days,
            )
            if new_metadata == metadata:
                continue
            data["metadata"] = new_metadata
            updated += 1
            if dry_run:
                LOGGER.info(
                    "[Backfill] would update %s: daily_stars=%s baseline=%s",
                    file_path,
                    new_metadata.get("daily_stars"),
                    new_metadata.get("stars_baseline_date"),
                )
                continue
            file_path.write_text(
                json.dumps(data, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
    return scanned, updated


def rebuild_index(articles_dir: Path, *, dry_run: bool) -> int:
    """Regenerate ``articles_dir/index.json`` from per-day files.

    Dedupe by ``source_url`` keeping the article with the latest
    ``collected_at`` value.

    Returns:
        Number of articles written to the index.
    """
    by_url: dict[str, dict[str, Any]] = {}
    for date_dir in sorted(articles_dir.glob(DATE_DIR_PATTERN)):
        if not date_dir.is_dir():
            continue
        for file_path in sorted(date_dir.glob("*.json")):
            try:
                data = json.loads(file_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            if not isinstance(data, dict):
                continue
            url = str(data.get("source_url") or data.get("id") or "")
            if not url:
                continue
            existing = by_url.get(url)
            if existing is None or _collected_at(data) > _collected_at(existing):
                by_url[url] = data

    items = sorted(
        by_url.values(),
        key=lambda x: _collected_at(x),
        reverse=True,
    )
    index_path = articles_dir / "index.json"
    if dry_run:
        LOGGER.info("[Backfill] would write %s with %s items", index_path, len(items))
        return len(items)
    index_path.write_text(
        json.dumps(items, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return len(items)


def _enrich_metadata(
    metadata: dict[str, Any],
    *,
    source_url: str,
    today_date: str,
    articles_dir: Path,
    max_lookback_days: int,
) -> dict[str, Any]:
    """Return a new metadata dict with daily-star fields filled in."""
    new_metadata = dict(metadata)
    current_stars = new_metadata.get("stars")
    baseline_stars, baseline_date = find_baseline_stars(
        source_url,
        today_date,
        articles_dir=articles_dir,
        max_lookback_days=max_lookback_days,
    )
    if isinstance(current_stars, int) and isinstance(baseline_stars, int):
        new_metadata["daily_stars"] = current_stars - baseline_stars
        new_metadata["stars_baseline_date"] = baseline_date
    else:
        new_metadata["daily_stars"] = None
        new_metadata["stars_baseline_date"] = baseline_date
    return new_metadata


def _collected_at(article: dict[str, Any]) -> str:
    return str(article.get("collected_at") or "")


def main() -> int:
    """Entry point."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    args = parse_args()

    scanned, updated = backfill_directory(
        args.articles_dir,
        max_lookback_days=args.max_lookback_days,
        dry_run=args.dry_run,
    )
    indexed = rebuild_index(args.articles_dir, dry_run=args.dry_run)

    LOGGER.info(
        "[Backfill] scanned=%s updated=%s indexed=%s dry_run=%s",
        scanned,
        updated,
        indexed,
        args.dry_run,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
